# -- compile --
FROM node:16-alpine AS compile
WORKDIR /app

# install dependecies
COPY package* .
RUN npm install

# copy rest
COPY . .

# compile
RUN npm run build

# -- run server --
FROM nginx:1.19 AS runner
WORKDIR /var
RUN rm -rf /usr/share/nginx/html
COPY --from=compile /app/build /usr/share/nginx/html
