# -- compile --
FROM node:16-alpine AS compile
WORKDIR /app

# install dependecies
COPY package* .
RUN npm install

# copy rest
COPY . .

# compile
RUN npm run build

# -- run server --
FROM nginx:1.19 AS runner
WORKDIR /var

# nginx cleanup
RUN rm -rf /usr/share/nginx/html
RUN rm -f /etc/nginx/conf.d/default.conf

# site config
COPY ./docker/site.conf /etc/nginx/conf.d/default.conf

# add built files
COPY --from=compile /app/build /usr/share/nginx/html

EXPOSE 80
